### ISSUE TITLE
ナビゲートバーの実装

### ISSUE THREAD

**Issue by kuroishihiromu** [EDD2024-start/StamComm#11]
## 目的
ナビゲートバーを実装する
## Issue分類
- [ ] 設計
- [X] 機能追加
- [ ] バグ修正

## チケットのゴール
ナビゲートバーを実装する
## 作業
- [ ] Navigate .dartを作成する。

**Comment by kuroishihiromu** [comment]
https://kawaedomain.com/2024/01/25/%E3%80%90flutter%E3%80%91%E3%83%95%E3%83%83%E3%82%BF%E3%83%BC%E3%81%AB%E3%83%8A%E3%83%93%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%83%9C%E3%82%BF%E3%83%B3%E3%82%92%E3%81%A4%E3%81%8F%E3%82%8B/#toc1

**Comment by repunit11** [comment]
lib/component/navigate.dartにナビゲートを追加します

**Comment by kuroishihiromu** [comment]
https://zenn.dev/heyhey1028/books/flutter-basics/viewer/navigation
