### ISSUE TITLE
アプリケーションのアイコンを変更する

### ISSUE THREAD

**Issue by meyuchan** [EDD2024-start/StamComm#33]
## 目的
アプリケーションのアイコンを変更する

## Issue分類
- [ ] 設計
- [x] 機能追加
- [ ] バグ修正

## 詳細
https://github.com/EDD2024-start/StamComm/issues/6#issuecomment-2335007105
こちらを参考にアイコンを変更する

## 作業
- [ ] タスク１
- [ ] タスク２

**Comment by hibiki1023k** [comment]
![image](https://github.com/user-attachments/assets/da200d79-f5de-4d2c-9e9b-299f434351ac)
アイコンこんな感じになってます〜
もうちょい縮小させましょうか

**Comment by meyuchan** [comment]
縮小お願いします〜

**Comment by hibiki1023k** [comment]
iosのアイコン地味に曲率が異なっててうまく適用できない
