### ISSUE TITLE
stamp情報をsupabaseから取得する

### ISSUE THREAD

**Issue by hibiki1023k** [EDD2024-start/StamComm#45]
## 目的
現状`assets/data/sample-data.json`に格納されているデータをsupabaseと同期させる

## Issue分類
- [ ] 設計
- [x] 機能追加
- [ ] バグ修正

## チケットのゴール
`sample-data.json`を使用せずにスタンプの押下をする

## 詳細
supabaseのstampについて、GETができる

## 作業
- [x] `display_map.dart`とsupabaseを紐づける
- [ ] stamp情報をsupabaseから取得する

**Comment by meyuchan** [comment]
イベントごとに表示できるようにする

**Comment by hibiki1023k** [comment]
supabaseからのスタンプ情報はissue36の分の差分で確認済み
