### ISSUE TITLE
2回目以降の取得の際に取得済みであることを示す

### ISSUE THREAD

**Issue by hibiki1023k** [EDD2024-start/StamComm#56]
## 目的
取得済みスタンプを再度取得したときの画面の挙動を見直す

## 親Issue
#54 

## Issue分類
- [ ] 設計
- [ ] 機能追加
- [x] バグ修正

## チケットのゴール
取得済みスタンプを再度取得したときにユーザーに誤解なく取得済みであることを示す

## 詳細
取得済みスタンプを再度取得したときに`stamp_success_screen.dart`が表示されないようにする、ダイアログの表示方法について見直す

## 作業
- [ ] `stamp_success_screen.dart`の非表示
- [ ] ダイアログ表示の改善

**Comment by meyuchan** [comment]
実装が変わったので、 @hibiki1023k が修正
