### ISSUE TITLE
使用アイコンの選定

### ISSUE THREAD

**Issue by meyuchan** [EDD2024-start/StamComm#6]
## 目的
StamCommのアイコンを決める

## Issue分類
- [x] 設計
- [ ] 機能追加
- [ ] バグ修正

## チケットのゴール
アイコンが決定する

## 詳細
アイコンが決まっていないのでせっかくならみんなで考えよう 💯 

## 作業
- [ ] アイコンを募集する
- [ ] アンケートを取る

**Comment by kuroishihiromu** [comment]
![StamCommIcon_4](https://github.com/user-attachments/assets/a7ffcee3-3df5-4a7d-a618-42ffd7dab6b3)
![StamCommTextIcon_1](https://github.com/user-attachments/assets/97949490-062a-4305-bf92-bc5190a413f3)
