### ISSUE TITLE
発表当日にやること

### ISSUE THREAD

**Issue by meyuchan** [EDD2024-start/StamComm#67]
- エンジニアカフェ周辺のスタンプの登録
- スタンプ取得までの流れを動画に撮る
- 発表資料作成

**Comment by kuroishihiromu** [comment]
イベント名 : EDD Fukuoka 2024
スタンプ1 : エンジニアコーヒーのスタンプ
スタンプ2 : エンジニアカフェ2階のスタンプ

例外出す用
イベント名 : アンパンマン
スタンプ1 : アンパン
