### ISSUE TITLE
display-mapの実装

### ISSUE THREAD

**Issue by hibiki1023k** [EDD2024-start/StamComm#9]
## 目的
スタンプの情報をマップ上で確認するためのページ(display-map)を実装する

## Issue分類
- [ ] 設計
- [x] 機能追加
- [ ] バグ修正

## チケットのゴール
Google MapのFlutterプラグインを使用して **作業** の要素を加えたdisplay-mapページを作成する

## 詳細
[Google Maps for Flutter](https://pub.dev/packages/google_maps_flutter)を使用すること
[【Flutter】GoogleMap for Flutter あれこれ(Zenn)](https://zenn.dev/slowhand/articles/f4e4e092f9b72b)とかも参考になるかも

## 作業
- [ ] Google Mapのビュー表示
- [ ] 端末の位置情報の表示
- [ ] NFCの位置情報（ピンを使って表示）
- [ ] NFCのピンをクリックして詳細のポップアップ表示

**Comment by kuroishihiromu** [comment]
~` /src/view/display-map.dart `~
` /src/view/display_map.dart `

**Comment by meyuchan** [comment]
@kuroishihiromu 
ファイル名は`-`が使えないようなので`/src/view/display_map.dart`に変更をお願いします！

**Comment by kuroishihiromu** [comment]
` /src/view/display-map.dart `
